name: telegram bot with test


on:
 push:
   branches: ['main']
 pull_request: ['main']
 

jobs:
  test:
    
    runs-on: ubuntu-latest


    strategy:
        matrix:
          node_version: [18.x,19.x,20.x]

    

    steps:
      - name: checkout krna hoga -uses (command se)  jo github pr uploaded hai actions/checkout@v4
      - uses: actions/checkout@v4
      - name: download node js 3 times  here with it version ${{matrix.node-version}}
      - uses: actions/setup-node@v4
        with: 
          node_version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm test