  name: telegram bot with test


  on:
   push:
    branches: ['main']
   pull_request:
    branches: ['main']
  

  jobs:
    test:
      
      runs-on: ubuntu-latest
      env: 
        NODE_ENV: test
        SHEET_ID: '1k5gahYFoiIK8zYJ_x4jkchj-OWj9w3SRsCDB3s_gYwc'
        TOKEN: '7829119683:AAFKKc4q10WzEHI6efNY1YcQNVgBCDabS2Y'
        MONGO_URI: 'mongodb+srv://shahansiddique101:shahan1234@cluster0.yeh6bzp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
        ADMIN_CHAT_ID: '1673569001'
        GOOGLE_CREDENTIALS_BASE64: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAib3JiaXRhbC1lZ28tNDY2MTA1LXM2IiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMTAwYTA2ZmUyZTc5YTczNWJiNWJmMTRmZDRiMzg5ZjNiNDQ4YjZlNyIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDNzFjY0hUc2RTQUg4alxuc3F0SnF1S20xcnJFblFic1NSWU0wV3lTekxHYzFMR3B1a0cxK2VzM3hJWWhONmFBcnpKZXY2eVpFREJaa1pITFxuNERjYThTNEpPSDlERGk0VzVRWXc3Q2g2OWdFalA1QUpEdWpiYkw1K3JlNTFUT25MdEtUY0hscEJ1OCttN2dUZVxuY25WTmRVdllYS0ZyMjZBTjB4NElwNFE5aGhURVJnYjlJa0ZVTWJMQXdRQ3RoMXFYalpITmpuTVkxRE91RGo2WlxuMSt4SW5NRXBYd2NKK3ZncUFTdmw4S1NKbGs3dzhlYllZbmRQeGRTY2duK1B2SjMxM2lCTzlVcDMvM1U0cDR1b1xucHo2SDdLanp1MGRwWkxSK3c2UmhkOU84R3hVQi8wbnI2TUNMdTdwUzczbXZKeXdKOFp4cmY4RjJuSFBoR2VpTlxuclpFN0VtbkhBZ01CQUFFQ2dnRUFCbVRENXdKVklkK0tyVHk2UElsZC82dWJzemVWanFHbXJ3eFlpUHVQMDBMblxuN1Q2OTV2alZsNkJCTmxPVG5CbjNBTmtVU1F1NTZaZnJjNHZsUW9NdUF2b2RjdGVsOGNCeW9FZDJDcDNodWdnMFxuTDBBVkFVQmtBajVSSzBUREVCVjN0Y2lldFRWdFF3eGNKNStUdzBMZmFVTXV6b3k3SmQxUjZ2TU5PdlE0TkJMelxuRGRVcnU3Q212TTJPQkNYRkFRblNidTBOeE1LY0F1dExjVjdER01JK1lBdlJFdFEzTTdPSGdDRDkzcnNxOVNKTFxud3lqVndzMWt3S0w0RWorczYrNW94ZkJnYnd5eTVRUFpQeVArQzZwd2RLanBSREd5WnhsQ2J4SmpXK3JhaXptOFxuaXplY2k5SStIUDFQaDNqUlZBMjQyd2p5RzFtRHRNOTNOU2gvRElFcUlRS0JnUUQ5eWlsdUtzK2RkVG5Rd3JsaFxuYVRLT2pRNkEwdGNoalFYWVJlZ0VLcGdwbjk4Z245bjZIcXl4cmp5RDBtU3dVYUx4KzBDSFAzQTJVOTZ2cTQvNlxuOVJKbURxbDdEOEl2M0lvNkpLc25iTHFtZzhSV3pSbHpVNE1KRG9nTVdDd21HUEgvcCtra3hNMFhaamNoTXdxNlxubGRLVHhoZ3Qwcmt5dXFNRVFOYmZFVTczdHdLQmdRQzllSkR0NUFtdTNhaUFKRTl0dnhYbVQ1RUVRc0hvUlZtOFxuQnVYcmtHRkoxb3RKSHl2ZGhyYVBTN3JWdTlzM2lPb0xnaFlXcWdkbmdKd3VxMWpjNHVod01USFJ2aUNDNCtwcFxuaWgyeGF6Q2VWTk9xcFo1ODNkNGJ6V2R2V1RsQm9SRDlKQU9kS3hPWW1HYVVDek5EeE9SM2JhcnNhcGNnQ1lBSVxuT1hDMEF3MStjUUtCZ0N1VnAyM1REbHExUWh1WEJXMDBPc2wrY2dvdnEyQ0lyb05JNWlLcENmN0VCUGErWFJuMlxuWUtRWER5OTRWM0JzWkxaMzlzb0RYQXNJZGtybkJOQU5mSDVvY0RUQkxSRTVKOGY2ZWlaSUp2bm4wVFV5L2ZidlxuVmFhZGgwSFBkcTJJUlM4cHNBRnZodVZJMlpqckFpR3ZEejN2bkVGcVdnSGJTWm0yWlBCa01aS2JBb0dCQUlJUVxueXdUVGZ5WXdlYVNGeUpUaEVTcUtRbFczY2g5OXhBMEVlejlMWE0zd1hxdHluNDB5Rmc2bWdQcUtQQUdTbG9BUlxuN0JIZzVMWlRubU9YTXFobmlBTEVjcHUyTmVGRWpqMm5GNTBjcFVKN250Wk5YVkFBaXFGeFR1a3NTZGJZdDYzZVxuMURCSFN1dDg2eVlEemt4ZVZDdjc5OUxWbFNyaitxVXFzVWlScytpeEFvR0JBT0NPRVhRUFNxclpBQTVhRTBFNVxuUXJvTFltZW9YbkRMMnJEb3BuMVhNeldZd2VnVzlkSGVSTnlNVTNSVlRrWG5lYXlLa290dTNyQ2ovTHFPcGt3TlxuMU1DbjJWUnE5cnZENno5dnhubkM4SGcrYlhlZEJicEtVeEMxWWZYdmMzUDNYWVUrWGcvRjZjZUhxUnZYWnZUbVxuZGVHWGhqc1RoTkhPSXN5bGxYYlFFL3BiXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAiaW50ZWdyYWwtcHlxc0BvcmJpdGFsLWVnby00NjYxMDUtczYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTA5NzQ3NDY1ODQ1Mjg5NDUxMTM5IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9pbnRlZ3JhbC1weXFzJTQwb3JiaXRhbC1lZ28tNDY2MTA1LXM2LmlhbS5nc2VydmljZWFjY291bnQuY29tIiwKICAidW5pdmVyc2VfZG9tYWluIjogImdvb2dsZWFwaXMuY29tIgp9Cg==
        GOOGLE_TOKEN: ewogICJhY2Nlc3NfdG9rZW4iOiAieWEyOS5BMEFTM0g2TnpNTkdnUG1sODlFMUJzUnVEZUJuTlBacDc0QjE0WHVzelY0Y3BJNHdHV2VDSW43YXdBMG1aQTVWZW1UQUZLQ2xIVk80ZG02SkRBR2ZJYmxjMC1NRUJpU3ExODU1MnNwampGMllMWkFEcmttVTB0NXV0TVRaMHV3bmZ1bExWTmlnN0UxelNFUVpObTk2UXBlb0pBb0dnTXV4b0s4VGFPRE5UOGwyMnBHcTNfZlZGcmN2cDdSNTF6VjVmSmFWQWJuYjhhQ2dZS0FUQVNBUkVTRlFIR1gyTWlKTzltcmNzVTVTcUstSGc3Mk5nSFpnMDIwNiIsCiAgInJlZnJlc2hfdG9rZW4iOiAiMS8vMGdlaGs1UW9QUG9DY0NnWUlBUkFBR0JBU053Ri1MOUlybEt3Nmd1T3o0aEtYQWVJZlNaM2ZES3pwbjFhOEk2ZGZrN3QyQU5iRkMweVpwWVRXakhBOE9UUllTLTlBSk0tbElKbyIsCiAgInNjb3BlIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL2F1dGgvZHJpdmUuZmlsZSIsCiAgInRva2VuX3R5cGUiOiAiQmVhcmVyIiwKICAiZXhwaXJ5X2RhdGUiOiAxNzUyOTI4Mjg4NDc0Cn0=
        GOOGLE_SECRET: eyJjbGllbnRfaWQiOiI0ODUzOTA4NTY3NDktbjdqam9tZ3E3bHBzYXRuajRwY2FhNWJmMHZoN2VjZXMuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJwcm9qZWN0X2lkIjoibmV3MS00NjY0MTEiLCJhdXRoX3VyaSI6Imh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwidG9rZW5fdXJpIjoiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLCJjbGllbnRfc2VjcmV0IjoiR09DU1BYLXFwRlk5ZTBad2MwSnpxdng0alNKdk1wVExxWW0iLCJyZWRpcmVjdF91cmlzIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDAwMC9vYXV0aDJjYWxsYmFjayJdfQ==



      strategy:
          matrix:
            node-version: [18.x, 20.x, 22.x]

      

      steps:
        - name: checkout krna hoga -uses (command se)  jo github pr uploaded hai actions/checkout@v4
          uses: actions/checkout@v4


        - name: download node js 3 times  here with it version ${{matrix.node-version}}
          uses: actions/setup-node@v4
          with: 
            node-version: ${{matrix.node-version}}
            cache: 'npm'
        - name: Install dependencies
          run: npm ci

        - name: Run tests
          run: npm test